changelog:
  exclude:
    labels: ["skip-changelog"]
  categories:
    - title: Provider and security changes
      labels: ["provider", "security", "dependencies"]
    - title: Other changes
      labels: ["*"]
