name: GCL conformance
on:
  pull_request:
  push:
    branches: [main]
  merge_group:
  schedule:
    - cron: "17 8 * * 1"
permissions:
  contents: read
concurrency:
  group: gcl-conformance-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  policy:
    uses: grandchallenge/.github/.github/workflows/gcl-policy.yml@f98003ef7f8a28ea774e82bf21ce0fe0323d1c28
    with:
      profile: Provider
      standards_ref: c5604226b306a1b6fe104757a3852ded5cba2bb9
  security:
    permissions:
      contents: read
    uses: grandchallenge/.github/.github/workflows/gcl-security.yml@f98003ef7f8a28ea774e82bf21ce0fe0323d1c28
